### ISSUE TITLE
Call to sample_distribution may return xarray.Variable

### ISSUE THREAD

**Issue by seidlj** [smartass101/xr-random#4] opened 2020-01-20 15:39 UTC
**Expected behavior:** `sample_distribution` always returns `xarray.DataArray`.

**Steps to reproduce:** Call `sample_distribution` with float/int shape parameters, e.g. `sample_distribution(stats.norm, loc=1)`, or even without any shape parameters `sample_distribution(stats.norm)`.

**Comment by smartass101** [comment] 2020-05-06 10:36
The issue is that I wrapped the virtual sample array in `Variable` here
https://github.com/smartass101/xr-random/blob/0867a7f8169f3915fb84721ab4553fc8043f5a11/xrrandom/sampling.py#L27
We could change that to `DataArray` which would entail a little loss of generality (e.g. if people were passing only `Variable` instances but I agree that it's probably more intuitive to always return `DataArray`

**Comment by smartass101** [comment] 2020-05-06 11:36
A possible fix is in bc8c7510ed209f6db213f4f94d7cfd2e3532e905. An alternative approach would be to check before return if the result is `DataArray`, this would be slightly more explicit and with perhaps less overhead. If we decide we always want to return DataArray, the alternaitve paproach is easier to implement everywhere, including in the stats API.

**Comment by smartass101** [comment] 2020-05-06 13:37
Fixed in https://github.com/smartass101/xr-random/commit/efaf2d73ae09fcd828224878835208e0077c1f00 by checking the return value of wrapped functions.

**Closed as completed by smartass101** 2020-05-06 13:37 UTC
